### ISSUE TITLE
forge server startup crash 1.19.4

### ISSUE THREAD

**Issue by crayolasunset** [jayhillx/MysticsBiomes#10]
Hi there! I have an issue currently when starting up a new forge 1.19.4 server that says Mystic's biomes has failed to load correctly. It sounds sort of similar to the 1.19.2 issue, except on 1.19.4 instead. Here is the crash log I am getting:

>  Crash Report UUID: 8b23c75f-344d-4d1b-93bd-06f7f256e9d7
        FML: 45.2
        Forge: net.minecraftforge:45.2.0[01:03:09] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Mystic's Biomes (mysticsbiomes) has failed to load correctly
§7java.lang.reflect.InvocationTargetException: null
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:240) ~[fmlcore-1.19.4-45.2.0.jar%23354!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$24(ModLoader.java:203) ~[fmlcore-1.19.4-45.2.0.jar%23354!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:203) ~[fmlcore-1.19.4-45.2.0.jar%23354!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$14(ModLoader.java:180) ~[fmlcore-1.19.4-45.2.0.jar%23354!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:180) ~[fmlcore-1.19.4-45.2.0.jar%23354!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.19.4-45.2.0-universal.jar%23358!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:125) ~[server-1.19.4-20230314.122934-srg.jar%23353!/:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.4-45.2.0.jar%2367!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

**Comment by jayhillx** [comment]
huh that’s weird, i thought that was only affecting 1.19.2! lemme check some things out and i’ll post a fixed version asap!

**Comment by jayhillx** [comment]
this issue was posted forever ago, but i will not be updating 1.19.4 again :(
i hope you were able to move your mods to a newer version!
