### ISSUE TITLE
Server crashes when loading mystic biomes 1.20.1 

### ISSUE THREAD

**Issue by kirbymuncher** [jayhillx/MysticsBiomes#13]
Hello, I started a forge-modded Minecraft server for 1.20.1, but when the game loads with mystic biomes, it seems to crash until the mod is removed. 
 
This is the link to the crash message:
![mystic biomes crash](https://github.com/jayhillx/MysticsBiomes/assets/152828989/a4373be3-93b8-4904-91c8-4464ab4dae6a)

Hopefully something could be worked out 😅😅

**Comment by Aceplante** [comment]
I got something about placed feature crash

**Comment by jayhillx** [comment]
sorry for a late response, im not seeing anything related to mystics biomes in that screenshot you attached at all? could you post the full crash report here?

**Comment by jayhillx** [comment]
> I got something about placed feature crash

are you also using 1.20.1? i know there were some issues with early 1.19.2 and 4 with crashing on servers.

**Comment by Aceplante** [comment]
> are you also using 1.20.1? i know there were some issues with early 1.19.2 and 4 with crashing on servers.

Yes I am using 1.20.1, hope this helps

```
Error executing task on Chunk source main thread executor for minecraft:overworld
java.util.concurrent.CompletionException: net.minecraft.ReportedException: Feature placement
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: net.minecraft.ReportedException: Feature placement
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:660)
	at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 11 more
Caused by: com.ishland.uwrad.common.CheckedThreadLocalRandom$1: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: Worker-Main-133)
Possible solutions: Find possible causes in the stack trace below and report to the corresponding mod authors 
 
 (You may make this a fatal warning instead of a hard crash with enforce_safe_world_random_access setting in uwrad.properties)
Caused by: java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: Worker-Main-133)
	at TRANSFORMER/unsafe_world_random_access_detector@1.1.0+forge/com.ishland.uwrad.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:51)
	at TRANSFORMER/unsafe_world_random_access_detector@1.1.0+forge/com.ishland.uwrad.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38)
	at TRANSFORMER/unsafe_world_random_access_detector@1.1.0+forge/com.ishland.uwrad.common.CheckedThreadLocalRandom.m_64707_(CheckedThreadLocalRandom.java:82)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.BitRandomSource.m_188501_(BitRandomSource.java:56)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.predicates.LootItemRandomChanceCondition.test(LootItemRandomChanceCondition.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.predicates.LootItemRandomChanceCondition.test(LootItemRandomChanceCondition.java:9)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer.m_79639_(LootPoolEntryContainer.java:34)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer.m_6562_(LootPoolSingletonContainer.java:67)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.LootPool.m_79058_(net/minecraft/world/level/storage/loot/LootPool.java:59)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.LootPool.m_79053_(net/minecraft/world/level/storage/loot/LootPool.java:94)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.LootTable.m_79131_(net/minecraft/world/level/storage/loot/LootTable.java:85)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.LootTable.m_230922_(net/minecraft/world/level/storage/loot/LootTable.java:117)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.storage.loot.LootTable.m_287195_(net/minecraft/world/level/storage/loot/LootTable.java:112)
	at TRANSFORMER/zillagersweararmor@1.20-1.3.2/tallestegg.illagersweararmor.IWASpawnEvents.getNaturalSpawnItemsFromLootTable(IWASpawnEvents.java:110)
	at TRANSFORMER/zillagersweararmor@1.20-1.3.2/tallestegg.illagersweararmor.IWASpawnEvents.giveArmorNaturally(IWASpawnEvents.java:133)
	at TRANSFORMER/zillagersweararmor@1.20-1.3.2/tallestegg.illagersweararmor.IWASpawnEvents.finalizeSpawn(IWASpawnEvents.java:66)
	at TRANSFORMER/zillagersweararmor@1.20-1.3.2/tallestegg.illagersweararmor.__IWASpawnEvents_finalizeSpawn_FinalizeSpawn.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.19/net.minecraftforge.event.ForgeEventFactory.onFinalizeSpawn(net/minecraftforge/event/ForgeEventFactory.java:281)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.structure.structures.SwampHutPiece.m_213694_(SwampHutPiece.java:116)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.levelgen.structure.StructureStart.m_226850_(StructureStart.java:90)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkGenerator.m_223080_(net/minecraft/world/level/chunk/ChunkGenerator.java:320)
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(net/minecraft/world/level/chunk/ChunkGenerator.java:319)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkStatus.m_279978_(net/minecraft/world/level/chunk/ChunkStatus.java:108)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.ChunkStatus.m_280308_(net/minecraft/world/level/chunk/ChunkStatus.java:252)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(net/minecraft/server/level/ChunkMap.java:643)
	at MC-BOOTSTRAP/datafixerupper@6.0.8/com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(net/minecraft/server/level/ChunkMap.java:634)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(net/minecraft/server/level/ChunkTaskPriorityQueueSorter.java:62)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by jayhillx** [comment]
hmm i don't see anything related to this mod in that either. the only thing i do see is potentially from the mod illagers wear armor?

**Comment by Aceplante** [comment]
I saw that too but its a client side entity mod that shouldnt affect placed features. Ill give it a try without it and let you know if I crash again

**Comment by jayhillx** [comment]
that's what i was thinking as well. it just seemed to be the only thing i was seeing. would you be able paste the entire crash report here?

**Comment by jayhillx** [comment]
bump

**Comment by jayhillx** [comment]
if youre still experiencing this, please resubmit another issue!
